/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGCSHARP


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_Engine(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_Engine(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_Engine(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13




#include <vector>
  

#include <stdexcept>


#include <string>


#include <vector>
#include <algorithm>
#include <stdexcept>


#include <map>
#include <algorithm>
#include <stdexcept>


SWIGINTERN void SWIG_CSharpException(int code, const char *msg) {
  if (code == SWIG_ValueError) {
    SWIG_CSharpExceptionArgumentCodes exception_code = SWIG_CSharpArgumentOutOfRangeException;
    SWIG_CSharpSetPendingExceptionArgument(exception_code, msg, 0);
  } else {
    SWIG_CSharpExceptionCodes exception_code = SWIG_CSharpApplicationException;
    switch(code) {
    case SWIG_MemoryError:
      exception_code = SWIG_CSharpOutOfMemoryException;
      break;
    case SWIG_IndexError:
      exception_code = SWIG_CSharpIndexOutOfRangeException;
      break;
    case SWIG_DivisionByZero:
      exception_code = SWIG_CSharpDivideByZeroException;
      break;
    case SWIG_IOError:
      exception_code = SWIG_CSharpIOException;
      break;
    case SWIG_OverflowError:
      exception_code = SWIG_CSharpOverflowException;
      break;
    case SWIG_RuntimeError:
    case SWIG_TypeError:
    case SWIG_SyntaxError:
    case SWIG_SystemError:
    case SWIG_UnknownError:
    default:
      exception_code = SWIG_CSharpApplicationException;
      break;
    }
    SWIG_CSharpSetPendingException(exception_code, msg);
  }
}


#include <stdexcept>


#include <utility>

SWIGINTERN std::vector< Component * > *new_std_vector_Sl_Component_Sm__Sg___SWIG_2(int capacity){
        std::vector< Component * >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< Component * >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN Component *std_vector_Sl_Component_Sm__Sg__getitemcopy(std::vector< Component * > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN Component *const &std_vector_Sl_Component_Sm__Sg__getitem(std::vector< Component * > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__setitem(std::vector< Component * > *self,int index,Component *const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__AddRange(std::vector< Component * > *self,std::vector< Component * > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< Component * > *std_vector_Sl_Component_Sm__Sg__GetRange(std::vector< Component * > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< Component * >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__Insert(std::vector< Component * > *self,int index,Component *const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__InsertRange(std::vector< Component * > *self,int index,std::vector< Component * > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__RemoveAt(std::vector< Component * > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__RemoveRange(std::vector< Component * > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< Component * > *std_vector_Sl_Component_Sm__Sg__Repeat(Component *const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< Component * >(count, value);
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__Reverse__SWIG_0(std::vector< Component * > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__Reverse__SWIG_1(std::vector< Component * > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_Component_Sm__Sg__SetRange(std::vector< Component * > *self,int index,std::vector< Component * > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }
SWIGINTERN bool std_vector_Sl_Component_Sm__Sg__Contains(std::vector< Component * > *self,Component *const &value){
        return std::find(self->begin(), self->end(), value) != self->end();
      }
SWIGINTERN int std_vector_Sl_Component_Sm__Sg__IndexOf(std::vector< Component * > *self,Component *const &value){
        int index = -1;
        std::vector< Component * >::iterator it = std::find(self->begin(), self->end(), value);
        if (it != self->end())
          index = (int)(it - self->begin());
        return index;
      }
SWIGINTERN int std_vector_Sl_Component_Sm__Sg__LastIndexOf(std::vector< Component * > *self,Component *const &value){
        int index = -1;
        std::vector< Component * >::reverse_iterator rit = std::find(self->rbegin(), self->rend(), value);
        if (rit != self->rend())
          index = (int)(self->rend() - 1 - rit);
        return index;
      }
SWIGINTERN bool std_vector_Sl_Component_Sm__Sg__Remove(std::vector< Component * > *self,Component *const &value){
        std::vector< Component * >::iterator it = std::find(self->begin(), self->end(), value);
        if (it != self->end()) {
          self->erase(it);
	  return true;
        }
        return false;
      }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_Clear(void * jarg1) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_Add(void * jarg1, void * jarg2) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  Component **arg2 = 0 ;
  Component *temp2 = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  temp2 = (Component *)jarg2;
  arg2 = (Component **)&temp2; 
  (arg1)->push_back((Component *const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_VectorComponent_size(void * jarg1) {
  unsigned long jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  std::vector< Component * >::size_type result;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  result = ((std::vector< Component * > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_VectorComponent_capacity(void * jarg1) {
  unsigned long jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  std::vector< Component * >::size_type result;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  result = ((std::vector< Component * > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_reserve(void * jarg1, unsigned long jarg2) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  std::vector< Component * >::size_type arg2 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (std::vector< Component * >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_VectorComponent__SWIG_0() {
  void * jresult ;
  std::vector< Component * > *result = 0 ;
  
  result = (std::vector< Component * > *)new std::vector< Component * >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_VectorComponent__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< Component * > *arg1 = 0 ;
  std::vector< Component * > *result = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Component * > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< Component * > *)new std::vector< Component * >((std::vector< Component * > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_VectorComponent__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< Component * > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< Component * > *)new_std_vector_Sl_Component_Sm__Sg___SWIG_2(arg1);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_VectorComponent_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  Component *result = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (Component *)std_vector_Sl_Component_Sm__Sg__getitemcopy(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_VectorComponent_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  Component **result = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (Component **) &std_vector_Sl_Component_Sm__Sg__getitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)*result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  Component **arg3 = 0 ;
  Component *temp3 = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  temp3 = (Component *)jarg3;
  arg3 = (Component **)&temp3; 
  try {
    std_vector_Sl_Component_Sm__Sg__setitem(arg1,arg2,(Component *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_AddRange(void * jarg1, void * jarg2) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  std::vector< Component * > *arg2 = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (std::vector< Component * > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Component * > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_Component_Sm__Sg__AddRange(arg1,(std::vector< Component * > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_VectorComponent_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< Component * > *result = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< Component * > *)std_vector_Sl_Component_Sm__Sg__GetRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  Component **arg3 = 0 ;
  Component *temp3 = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  temp3 = (Component *)jarg3;
  arg3 = (Component **)&temp3; 
  try {
    std_vector_Sl_Component_Sm__Sg__Insert(arg1,arg2,(Component *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  std::vector< Component * > *arg3 = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Component * > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Component * > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Component_Sm__Sg__InsertRange(arg1,arg2,(std::vector< Component * > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_RemoveAt(void * jarg1, int jarg2) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_Component_Sm__Sg__RemoveAt(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Component_Sm__Sg__RemoveRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void * SWIGSTDCALL CSharp_VectorComponent_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  Component **arg1 = 0 ;
  int arg2 ;
  Component *temp1 = 0 ;
  std::vector< Component * > *result = 0 ;
  
  temp1 = (Component *)jarg1;
  arg1 = (Component **)&temp1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Component * > *)std_vector_Sl_Component_Sm__Sg__Repeat((Component *const &)*arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_Reverse__SWIG_0(void * jarg1) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  std_vector_Sl_Component_Sm__Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_Component_Sm__Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_VectorComponent_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  int arg2 ;
  std::vector< Component * > *arg3 = 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Component * > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Component * > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_Component_Sm__Sg__SetRange(arg1,arg2,(std::vector< Component * > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_VectorComponent_Contains(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  Component **arg2 = 0 ;
  Component *temp2 = 0 ;
  bool result;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  temp2 = (Component *)jarg2;
  arg2 = (Component **)&temp2; 
  result = (bool)std_vector_Sl_Component_Sm__Sg__Contains(arg1,(Component *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_VectorComponent_IndexOf(void * jarg1, void * jarg2) {
  int jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  Component **arg2 = 0 ;
  Component *temp2 = 0 ;
  int result;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  temp2 = (Component *)jarg2;
  arg2 = (Component **)&temp2; 
  result = (int)std_vector_Sl_Component_Sm__Sg__IndexOf(arg1,(Component *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_VectorComponent_LastIndexOf(void * jarg1, void * jarg2) {
  int jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  Component **arg2 = 0 ;
  Component *temp2 = 0 ;
  int result;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  temp2 = (Component *)jarg2;
  arg2 = (Component **)&temp2; 
  result = (int)std_vector_Sl_Component_Sm__Sg__LastIndexOf(arg1,(Component *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_VectorComponent_Remove(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  Component **arg2 = 0 ;
  Component *temp2 = 0 ;
  bool result;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  temp2 = (Component *)jarg2;
  arg2 = (Component **)&temp2; 
  result = (bool)std_vector_Sl_Component_Sm__Sg__Remove(arg1,(Component *const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_VectorComponent(void * jarg1) {
  std::vector< Component * > *arg1 = (std::vector< Component * > *) 0 ;
  
  arg1 = (std::vector< Component * > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Component() {
  void * jresult ;
  Component *result = 0 ;
  
  result = (Component *)new Component();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Component(void * jarg1) {
  Component *arg1 = (Component *) 0 ;
  
  arg1 = (Component *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_TransformationComponent() {
  void * jresult ;
  TransformationComponent *result = 0 ;
  
  result = (TransformationComponent *)new TransformationComponent();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_TransformationComponent(void * jarg1) {
  TransformationComponent *arg1 = (TransformationComponent *) 0 ;
  
  arg1 = (TransformationComponent *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TransformationComponent_x_set(void * jarg1, int jarg2) {
  TransformationComponent *arg1 = (TransformationComponent *) 0 ;
  int arg2 ;
  
  arg1 = (TransformationComponent *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_TransformationComponent_x_get(void * jarg1) {
  int jresult ;
  TransformationComponent *arg1 = (TransformationComponent *) 0 ;
  int result;
  
  arg1 = (TransformationComponent *)jarg1; 
  result = (int) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TransformationComponent_y_set(void * jarg1, int jarg2) {
  TransformationComponent *arg1 = (TransformationComponent *) 0 ;
  int arg2 ;
  
  arg1 = (TransformationComponent *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_TransformationComponent_y_get(void * jarg1) {
  int jresult ;
  TransformationComponent *arg1 = (TransformationComponent *) 0 ;
  int result;
  
  arg1 = (TransformationComponent *)jarg1; 
  result = (int) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_TransformationComponent_z_set(void * jarg1, int jarg2) {
  TransformationComponent *arg1 = (TransformationComponent *) 0 ;
  int arg2 ;
  
  arg1 = (TransformationComponent *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_TransformationComponent_z_get(void * jarg1) {
  int jresult ;
  TransformationComponent *arg1 = (TransformationComponent *) 0 ;
  int result;
  
  arg1 = (TransformationComponent *)jarg1; 
  result = (int) ((arg1)->z);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Entity() {
  void * jresult ;
  Entity *result = 0 ;
  
  result = (Entity *)new Entity();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Entity(void * jarg1) {
  Entity *arg1 = (Entity *) 0 ;
  
  arg1 = (Entity *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Entity_addComponent(void * jarg1, void * jarg2) {
  Entity *arg1 = (Entity *) 0 ;
  Component *arg2 = (Component *) 0 ;
  
  arg1 = (Entity *)jarg1; 
  arg2 = (Component *)jarg2; 
  (arg1)->addComponent(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Entity_getComponents(void * jarg1) {
  void * jresult ;
  Entity *arg1 = (Entity *) 0 ;
  std::vector< Component * > result;
  
  arg1 = (Entity *)jarg1; 
  result = (arg1)->getComponents();
  jresult = new std::vector< Component * >((const std::vector< Component * > &)result); 
  return jresult;
}


SWIGEXPORT Component * SWIGSTDCALL CSharp_TransformationComponent_SWIGUpcast(TransformationComponent *jarg1) {
    return (Component *)jarg1;
}

#ifdef __cplusplus
}
#endif

